### ISSUE TITLE
Unreal Engine 5.1 and 5.2 ports for this?

### ISSUE THREAD

**Issue by BlueprintBailey** [YakuzaBalooza/Dash-Engine-1.3#2]
@YakuzaBalooza Hi, I've been currently working with UE5.2, and I'd appreciate it if you could at least try and port your Dash Engine 1.3 thing to 5.1 and 5.2 so people using higher stuff like me can have a chance without pulling our hairs doing it ourselves.

Good luck, and thanks in advance if you're able to do it.

**Comment by YakuzaBalooza** [comment]
At this point in time I will not be able to do a port of Dash Engine to UE5. This would require redoing every particle, as Cascade has been replaced and removed by Niagara in UE5, and possibly other things and I sadly don't have the time or energy currently due to starting college.
For the time being, you'll have to use UE4.27. My apologies if this causes issues.
